
--- autogenerated lush spec on Ut 16. apríl 2024, 11:05:42

local lush = require("lush")
local hsl = lush.hsl
local hsluv = lush.hsluv
local theme = lush(function(injected_functions)
  local sym = injected_functions.sym
  return {
    SpecialKey                             { fg="cyan", }, -- SpecialKey     xxx ctermfg=81 guifg=Cyan
    TermCursor                             { gui="reverse", }, -- TermCursor     xxx cterm=reverse gui=reverse
    NonText                                { fg="#8356a0", gui="bold", }, -- NonText        xxx ctermfg=12 gui=bold guifg=Blue
    EndOfBuffer                            { NonText }, -- EndOfBuffer    xxx links to NonText
    Whitespace                             { NonText }, -- Whitespace     xxx links to NonText
    TelescopePromptCounter                 { NonText }, -- TelescopePromptCounter xxx links to NonText
    TelescopePreviewHyphen                 { NonText }, -- TelescopePreviewHyphen xxx links to NonText
    TelescopeResultsDiffUntracked          { NonText }, -- TelescopeResultsDiffUntracked xxx links to NonText
    Directory                              { fg="", }, -- Directory      xxx ctermfg=159 guifg=Cyan
    TelescopePreviewDirectory              { Directory }, -- TelescopePreviewDirectory xxx links to Directory
    TelescopePreviewDate                   { Directory }, -- TelescopePreviewDate xxx links to Directory
    netrwDir                               { Directory }, -- netrwDir       xxx links to Directory
    ErrorMsg                               { fg="white", bg="red", }, -- ErrorMsg       xxx ctermfg=15 ctermbg=1 guifg=White guibg=Red
    NvimInvalidSpacing                     { ErrorMsg }, -- NvimInvalidSpacing xxx links to ErrorMsg
    IncSearch                              { fg="#020203", bg="#605dac", }, -- IncSearch      xxx guifg=#020203 guibg=#605dac
    MoreMsg                                { fg="seagreen", gui="bold", }, -- MoreMsg        xxx ctermfg=121 gui=bold guifg=SeaGreen
    ModeMsg                                { gui="bold", }, -- ModeMsg        xxx cterm=bold gui=bold
    LineNr                                 { fg="#6c2693", gui="italic", }, -- LineNr         xxx cterm=italic gui=italic guifg=#4c2673
    LineNrAbove                            { LineNr }, -- LineNrAbove    xxx links to LineNr
    LineNrBelow                            { LineNr }, -- LineNrBelow    xxx links to LineNr
    TelescopeResultsLineNr                 { LineNr }, -- TelescopeResultsLineNr xxx links to LineNr
    CursorLineNr                           { fg="#56004e", gui="italic", }, -- CursorLineNr   xxx cterm=italic gui=italic guifg=#56004e
    Question                               { fg="green", gui="bold", }, -- Question       xxx ctermfg=121 gui=bold guifg=Green
    netrwSymLink                           { Question }, -- netrwSymLink   xxx links to Question
    StatusLine                             { gui="bold,reverse", }, -- StatusLine     xxx cterm=bold,reverse gui=bold,reverse
    MsgSeparator                           { StatusLine }, -- MsgSeparator   xxx links to StatusLine
    StatusLineNC                           { gui="reverse", }, -- StatusLineNC   xxx cterm=reverse gui=reverse
    Title                                  { fg="magenta", gui="bold", }, -- Title          xxx ctermfg=225 gui=bold guifg=Magenta
    FloatTitle                             { Title }, -- FloatTitle     xxx links to Title
    sym"@text.title"                       { Title }, -- @text.title    xxx links to Title
    LspInfoTitle                           { Title }, -- LspInfoTitle   xxx links to Title
    Visual                                 { fg="#1a0016", bg="#730099", }, -- Visual         xxx guifg=#1a0016 guibg=#730099
    TelescopePreviewLine                   { Visual }, -- TelescopePreviewLine xxx links to Visual
    WarningMsg                             { fg="red", }, -- WarningMsg     xxx ctermfg=224 guifg=Red
    netrwCoreDump                          { WarningMsg }, -- netrwCoreDump  xxx links to WarningMsg
    WildMenu                               { fg="black", bg="#c959c1", }, -- WildMenu       xxx ctermfg=0 ctermbg=11 guifg=Black guibg=Yellow
    Folded                                 { fg="#af50af", bg="#310038", }, -- Folded         xxx ctermfg=14 ctermbg=242 guifg=Cyan guibg=DarkGrey
    netrwData                              { Folded }, -- netrwData      xxx links to Folded
    FoldColumn                             { fg="cyan", bg="grey", }, -- FoldColumn     xxx ctermfg=14 ctermbg=242 guifg=Cyan guibg=Grey
    CursorLineFold                         { FoldColumn }, -- CursorLineFold xxx links to FoldColumn
    DiffAdd                                { bg="darkblue", }, -- DiffAdd        xxx ctermbg=4 guibg=DarkBlue
    TelescopeResultsDiffAdd                { DiffAdd }, -- TelescopeResultsDiffAdd xxx links to DiffAdd
    DiffChange                             { bg="darkmagenta", }, -- DiffChange     xxx ctermbg=5 guibg=DarkMagenta
    TelescopeResultsDiffChange             { DiffChange }, -- TelescopeResultsDiffChange xxx links to DiffChange
    netrwLib                               { DiffChange }, -- netrwLib       xxx links to DiffChange
    netrwMakefile                          { DiffChange }, -- netrwMakefile  xxx links to DiffChange
    DiffDelete                             { fg="blue", bg="darkcyan", gui="bold", }, -- DiffDelete     xxx ctermfg=12 ctermbg=6 gui=bold guifg=Blue guibg=DarkCyan
    TelescopeResultsDiffDelete             { DiffDelete }, -- TelescopeResultsDiffDelete xxx links to DiffDelete
    DiffText                               { bg="red", gui="bold", }, -- DiffText       xxx cterm=bold ctermbg=9 gui=bold guibg=Red
    SignColumn                             { fg="cyan", bg="grey", }, -- SignColumn     xxx ctermfg=14 ctermbg=242 guifg=Cyan guibg=Grey
    CursorLineSign                         { SignColumn }, -- CursorLineSign xxx links to SignColumn
    Conceal                                { fg="lightgrey", bg="darkgrey", }, -- Conceal        xxx ctermfg=7 ctermbg=242 guifg=LightGrey guibg=DarkGrey
    SpellBad                               { gui="undercurl", sp="red", }, -- SpellBad       xxx ctermbg=9 gui=undercurl guisp=Red
    SpellCap                               { gui="undercurl", sp="blue", }, -- SpellCap       xxx ctermbg=12 gui=undercurl guisp=Blue
    SpellRare                              { gui="undercurl", sp="magenta", }, -- SpellRare      xxx ctermbg=13 gui=undercurl guisp=Magenta
    SpellLocal                             { gui="undercurl", sp="cyan", }, -- SpellLocal     xxx ctermbg=14 gui=undercurl guisp=Cyan
    Pmenu                                  { bg="magenta", }, -- Pmenu          xxx ctermfg=0 ctermbg=13 guibg=Magenta
    PmenuKind                              { Pmenu }, -- PmenuKind      xxx links to Pmenu
    PmenuExtra                             { Pmenu }, -- PmenuExtra     xxx links to Pmenu
    NormalFloat                            { Pmenu }, -- NormalFloat    xxx links to Pmenu
    PmenuSel                               { bg="darkgrey", }, -- PmenuSel       xxx ctermfg=242 ctermbg=0 guibg=DarkGrey
    PmenuKindSel                           { PmenuSel }, -- PmenuKindSel   xxx links to PmenuSel
    PmenuExtraSel                          { PmenuSel }, -- PmenuExtraSel  xxx links to PmenuSel
    PmenuSbar                              { bg="grey", }, -- PmenuSbar      xxx ctermbg=248 guibg=Grey
    PmenuThumb                             { bg="white", }, -- PmenuThumb     xxx ctermbg=15 guibg=White
    TabLine                                { bg="darkgrey", gui="underline", }, -- TabLine        xxx cterm=underline ctermfg=15 ctermbg=242 gui=underline guibg=DarkGrey
    TabLineSel                             { gui="bold", }, -- TabLineSel     xxx cterm=bold gui=bold
    netrwMarkFile                          { TabLineSel }, -- netrwMarkFile  xxx links to TabLineSel
    TabLineFill                            { gui="reverse", }, -- TabLineFill    xxx cterm=reverse gui=reverse
    CursorLine                             { bg="#4d0042", }, -- CursorLine     xxx guibg=#4d0042
    CursorColumn                           { CursorLine }, -- CursorColumn   xxx links to CursorLine
    ColorColumn                            { bg="darkred", }, -- ColorColumn    xxx ctermbg=1 guibg=DarkRed
    WinBar                                 { gui="bold", }, -- WinBar         xxx cterm=bold gui=bold
    WinBarNC                               { WinBar }, -- WinBarNC       xxx links to WinBar
    Cursor                                 { fg="bg", bg="fg", }, -- Cursor         xxx guifg=bg guibg=fg
    lCursor                                { fg="bg", bg="fg", }, -- lCursor        xxx guifg=bg guibg=fg
    Normal                                 { fg="#730099", bg="#210028", }, -- Normal         xxx guifg=#730099 guibg=#1a0016
    VertSplit                              { Normal }, -- VertSplit      xxx links to Normal
    NvimSpacing                            { Normal }, -- NvimSpacing    xxx links to Normal
    TelescopeNormal                        { Normal }, -- TelescopeNormal xxx links to Normal
    FloatShadow                            { bg="black", blend=80, }, -- FloatShadow    xxx guibg=Black blend=80
    FloatShadowThrough                     { bg="black", blend=100, }, -- FloatShadowThrough xxx guibg=Black blend=100
    RedrawDebugNormal                      { gui="reverse", }, -- RedrawDebugNormal xxx cterm=reverse gui=reverse
    RedrawDebugClear                       { bg="yellow", }, -- RedrawDebugClear xxx ctermbg=11 guibg=Yellow
    RedrawDebugComposed                    { bg="green", }, -- RedrawDebugComposed xxx ctermbg=10 guibg=Green
    RedrawDebugRecompose                   { bg="red", }, -- RedrawDebugRecompose xxx ctermbg=9 guibg=Red
    Error                                  { fg="white", bg="red", }, -- Error          xxx ctermfg=15 ctermbg=9 guifg=White guibg=Red
    NvimInvalid                            { Error }, -- NvimInvalid    xxx links to Error
    luaParenError                          { Error }, -- luaParenError  xxx links to Error
    luaError                               { Error }, -- luaError       xxx links to Error
    Todo                                   { fg="blue", bg="yellow", }, -- Todo           xxx ctermfg=0 ctermbg=11 guifg=Blue guibg=Yellow
    sym"@text.todo"                        { Todo }, -- @text.todo     xxx links to Todo
    luaTodo                                { Todo }, -- luaTodo        xxx links to Todo
    Constant                               { fg="#af60a0", }, -- Constant       xxx ctermfg=13 guifg=#ffa0a0
    String                                 { Constant }, -- String         xxx links to Constant
    Character                              { Constant }, -- Character      xxx links to Constant
    Number                                 { Constant }, -- Number         xxx links to Constant
    Boolean                                { Constant }, -- Boolean        xxx links to Constant
    sym"@constant"                         { Constant }, -- @constant      xxx links to Constant
    TelescopePreviewPipe                   { Constant }, -- TelescopePreviewPipe xxx links to Constant
    TelescopePreviewCharDev                { Constant }, -- TelescopePreviewCharDev xxx links to Constant
    TelescopePreviewBlock                  { Constant }, -- TelescopePreviewBlock xxx links to Constant
    TelescopePreviewRead                   { Constant }, -- TelescopePreviewRead xxx links to Constant
    TelescopePreviewUser                   { Constant }, -- TelescopePreviewUser xxx links to Constant
    TelescopePreviewGroup                  { Constant }, -- TelescopePreviewGroup xxx links to Constant
    TelescopeResultsConstant               { Constant }, -- TelescopeResultsConstant xxx links to Constant
    luaConstant                            { Constant }, -- luaConstant    xxx links to Constant
    Identifier                             { fg="#924c9d", }, -- Identifier     xxx cterm=bold ctermfg=14 guifg=#40ffff
    Function                               { Identifier }, -- Function       xxx links to Identifier
    sym"@parameter"                        { Identifier }, -- @parameter     xxx links to Identifier
    sym"@field"                            { Identifier }, -- @field         xxx links to Identifier
    sym"@property"                         { Identifier }, -- @property      xxx links to Identifier
    sym"@variable"                         { Identifier }, -- @variable      xxx links to Identifier
    sym"@namespace"                        { Identifier }, -- @namespace     xxx links to Identifier
    sym"@lsp.type.variable"                { Identifier }, -- @lsp.type.variable xxx links to Identifier
    NvimIdentifier                         { Identifier }, -- NvimIdentifier xxx links to Identifier
    TelescopeMultiIcon                     { Identifier }, -- TelescopeMultiIcon xxx links to Identifier
    TelescopePromptPrefix                  { Identifier }, -- TelescopePromptPrefix xxx links to Identifier
    TelescopeResultsIdentifier             { Identifier }, -- TelescopeResultsIdentifier xxx links to Identifier
    netrwVersion                           { Identifier }, -- netrwVersion   xxx links to Identifier
    luaFunc                                { Identifier }, -- luaFunc        xxx links to Identifier
    Statement                              { fg="#a361c3", gui="bold", }, -- Statement      xxx ctermfg=11 gui=bold guifg=#ffff60
    Conditional                            { Statement }, -- Conditional    xxx links to Statement
    Repeat                                 { Statement }, -- Repeat         xxx links to Statement
    Label                                  { Statement }, -- Label          xxx links to Statement
    Operator                               { Statement }, -- Operator       xxx links to Statement
    Keyword                                { Statement }, -- Keyword        xxx links to Statement
    Exception                              { Statement }, -- Exception      xxx links to Statement
    TelescopePreviewSocket                 { Statement }, -- TelescopePreviewSocket xxx links to Statement
    TelescopePreviewWrite                  { Statement }, -- TelescopePreviewWrite xxx links to Statement
    netrwHidePat                           { Statement }, -- netrwHidePat   xxx links to Statement
    netrwList                              { Statement }, -- netrwList      xxx links to Statement
    luaStatement                           { Statement }, -- luaStatement   xxx links to Statement
    PreProc                                { fg="#ff80ff", }, -- PreProc        xxx ctermfg=81 guifg=#ff80ff
    Include                                { PreProc }, -- Include        xxx links to PreProc
    Define                                 { PreProc }, -- Define         xxx links to PreProc
    Macro                                  { PreProc }, -- Macro          xxx links to PreProc
    PreCondit                              { PreProc }, -- PreCondit      xxx links to PreProc
    sym"@preproc"                          { PreProc }, -- @preproc       xxx links to PreProc
    netrwExe                               { PreProc }, -- netrwExe       xxx links to PreProc
    Type                                   { fg="#600060", gui="bold", }, -- Type           xxx ctermfg=121 gui=bold guifg=#60ff60
    StorageClass                           { Type }, -- StorageClass   xxx links to Type
    Structure                              { Type }, -- Structure      xxx links to Type
    Typedef                                { Type }, -- Typedef        xxx links to Type
    sym"@type"                             { Type }, -- @type          xxx links to Type
    sym"@lsp.type.type"                    { Type }, -- @lsp.type.type xxx links to Type
    NvimNumberPrefix                       { Type }, -- NvimNumberPrefix xxx links to Type
    NvimOptionSigil                        { Type }, -- NvimOptionSigil xxx links to Type
    LspInfoFiletype                        { Type }, -- LspInfoFiletype xxx links to Type
    TelescopeMultiSelection                { Type }, -- TelescopeMultiSelection xxx links to Type
    Special                                { fg="#cf0fa0", }, -- Special        xxx ctermfg=224 guifg=Orange
    Tag                                    { Special }, -- Tag            xxx links to Special
    SpecialChar                            { Special }, -- SpecialChar    xxx links to Special
    Delimiter                              { Special }, -- Delimiter      xxx links to Special
    SpecialComment                         { Special }, -- SpecialComment xxx links to Special
    Debug                                  { Special }, -- Debug          xxx links to Special
    sym"@constant.builtin"                 { Special }, -- @constant.builtin xxx links to Special
    sym"@function.builtin"                 { Special }, -- @function.builtin xxx links to Special
    sym"@constructor"                      { Special }, -- @constructor   xxx links to Special
    TelescopePreviewLink                   { Special }, -- TelescopePreviewLink xxx links to Special
    netrwLink                              { Special }, -- netrwLink      xxx links to Special
    netrwTreeBar                           { Special }, -- netrwTreeBar   xxx links to Special
    netrwPix                               { Special }, -- netrwPix       xxx links to Special
    DiagnosticError                        { fg="#ff0000", }, -- DiagnosticError xxx ctermfg=1 guifg=Red
    DiagnosticVirtualTextError             { DiagnosticError }, -- DiagnosticVirtualTextError xxx links to DiagnosticError
    DiagnosticFloatingError                { DiagnosticError }, -- DiagnosticFloatingError xxx links to DiagnosticError
    DiagnosticSignError                    { DiagnosticError }, -- DiagnosticSignError xxx links to DiagnosticError
    DiagnosticWarn                         { fg="#af3030", }, -- DiagnosticWarn xxx ctermfg=3 guifg=Orange
    DiagnosticVirtualTextWarn              { DiagnosticWarn }, -- DiagnosticVirtualTextWarn xxx links to DiagnosticWarn
    DiagnosticFloatingWarn                 { DiagnosticWarn }, -- DiagnosticFloatingWarn xxx links to DiagnosticWarn
    DiagnosticSignWarn                     { DiagnosticWarn }, -- DiagnosticSignWarn xxx links to DiagnosticWarn
    DiagnosticInfo                         { fg="#cf6080", }, -- DiagnosticInfo xxx ctermfg=4 guifg=LightBlue
    DiagnosticVirtualTextInfo              { DiagnosticInfo }, -- DiagnosticVirtualTextInfo xxx links to DiagnosticInfo
    DiagnosticFloatingInfo                 { DiagnosticInfo }, -- DiagnosticFloatingInfo xxx links to DiagnosticInfo
    DiagnosticSignInfo                     { DiagnosticInfo }, -- DiagnosticSignInfo xxx links to DiagnosticInfo
    DiagnosticHint                         { fg="#cf309f", }, -- DiagnosticHint xxx ctermfg=7 guifg=LightGrey
    DiagnosticVirtualTextHint              { DiagnosticHint }, -- DiagnosticVirtualTextHint xxx links to DiagnosticHint
    DiagnosticFloatingHint                 { DiagnosticHint }, -- DiagnosticFloatingHint xxx links to DiagnosticHint
    DiagnosticSignHint                     { DiagnosticHint }, -- DiagnosticSignHint xxx links to DiagnosticHint
    DiagnosticOk                           { fg="#ff60af", }, -- DiagnosticOk   xxx ctermfg=10 guifg=LightGreen
    DiagnosticVirtualTextOk                { DiagnosticOk }, -- DiagnosticVirtualTextOk xxx links to DiagnosticOk
    DiagnosticFloatingOk                   { DiagnosticOk }, -- DiagnosticFloatingOk xxx links to DiagnosticOk
    DiagnosticSignOk                       { DiagnosticOk }, -- DiagnosticSignOk xxx links to DiagnosticOk
    DiagnosticUnderlineError               { gui="underline", sp="red", }, -- DiagnosticUnderlineError xxx cterm=underline gui=underline guisp=Red
    DiagnosticUnderlineWarn                { gui="underline", sp="orange", }, -- DiagnosticUnderlineWarn xxx cterm=underline gui=underline guisp=Orange
    DiagnosticUnderlineInfo                { gui="underline", sp="lightblue", }, -- DiagnosticUnderlineInfo xxx cterm=underline gui=underline guisp=LightBlue
    DiagnosticUnderlineHint                { gui="underline", sp="lightgrey", }, -- DiagnosticUnderlineHint xxx cterm=underline gui=underline guisp=LightGrey
    DiagnosticUnderlineOk                  { gui="underline", sp="lightgreen", }, -- DiagnosticUnderlineOk xxx cterm=underline gui=underline guisp=LightGreen
    DiagnosticDeprecated                   { gui="strikethrough", sp="red", }, -- DiagnosticDeprecated xxx cterm=strikethrough gui=strikethrough guisp=Red
    Comment                                { fg="#4a2093", }, -- Comment        xxx guifg=#4c2673
    DiagnosticUnnecessary                  { Comment }, -- DiagnosticUnnecessary xxx links to Comment
    sym"@text.literal"                     { Comment }, -- @text.literal  xxx links to Comment
    sym"@comment"                          { Comment }, -- @comment       xxx links to Comment
    LspInfoTip                             { Comment }, -- LspInfoTip     xxx links to Comment
    TelescopeResultsComment                { Comment }, -- TelescopeResultsComment xxx links to Comment
    netrwComment                           { Comment }, -- netrwComment   xxx links to Comment
    luaComment                             { Comment }, -- luaComment     xxx links to Comment
    Underlined                             { fg="#80a0ff", gui="underline", }, -- Underlined     xxx cterm=underline ctermfg=81 gui=underline guifg=#80a0ff
    sym"@text.uri"                         { Underlined }, -- @text.uri      xxx links to Underlined
    MatchParen                             { bg="#9a409a", }, -- MatchParen     xxx ctermbg=6 guibg=DarkCyan
    Ignore                                 { fg="bg", }, -- Ignore         xxx ctermfg=0 guifg=bg
    NvimInternalError                      { fg="red", bg="red", }, -- NvimInternalError xxx ctermfg=9 ctermbg=9 guifg=Red guibg=Red
    NvimFigureBrace                        { NvimInternalError }, -- NvimFigureBrace xxx links to NvimInternalError
    NvimSingleQuotedUnknownEscape          { NvimInternalError }, -- NvimSingleQuotedUnknownEscape xxx links to NvimInternalError
    NvimInvalidSingleQuotedUnknownEscape   { NvimInternalError }, -- NvimInvalidSingleQuotedUnknownEscape xxx links to NvimInternalError
    minimapCursor                          { fg="#000000", bg="#af5f8f", }, -- minimapCursor  xxx ctermfg=228 ctermbg=59 guifg=#ffff87 guibg=#5f5f5f
    minimapRange                           { fg="#ffff87", bg="#4f4f4f", }, -- minimapRange   xxx ctermfg=228 ctermbg=242 guifg=#ffff87 guibg=#4f4f4f
    minimapDiffRemoved                     { fg="#fc1a70", }, -- minimapDiffRemoved xxx ctermfg=197 guifg=#fc1a70
    minimapDiffAdded                       { fg="#a4e400", }, -- minimapDiffAdded xxx ctermfg=148 guifg=#a4e400
    minimapDiffLine                        { fg="#af87ff", }, -- minimapDiffLine xxx ctermfg=141 guifg=#af87ff
    minimapCursorDiffRemoved               { fg="#fc1a70", bg="#5f5f5f", }, -- minimapCursorDiffRemoved xxx ctermfg=197 ctermbg=59 guifg=#fc1a70 guibg=#5f5f5f
    minimapCursorDiffAdded                 { fg="#a4e400", bg="#5f5f5f", }, -- minimapCursorDiffAdded xxx ctermfg=148 ctermbg=59 guifg=#a4e400 guibg=#5f5f5f
    minimapCursorDiffLine                  { fg="#af87ff", bg="#5f5f5f", }, -- minimapCursorDiffLine xxx ctermfg=141 ctermbg=59 guifg=#af87ff guibg=#5f5f5f
    minimapRangeDiffRemoved                { fg="#fc1a70", bg="#4f4f4f", }, -- minimapRangeDiffRemoved xxx ctermfg=197 ctermbg=242 guifg=#fc1a70 guibg=#4f4f4f
    minimapRangeDiffAdded                  { fg="#a4e400", bg="#4f4f4f", }, -- minimapRangeDiffAdded xxx ctermfg=148 ctermbg=242 guifg=#a4e400 guibg=#4f4f4f
    minimapRangeDiffLine                   { fg="#af87ff", bg="#4f4f4f", }, -- minimapRangeDiffLine xxx ctermfg=141 ctermbg=242 guifg=#af87ff guibg=#4f4f4f
    search_base                            { fg="#18171c", bg="#6d5dac", }, -- search_base    xxx guifg=#18171c guibg=#6d5dac
    Search                                 { search_base }, -- Search         xxx links to search_base
    lushify_FF0000                         { fg="#000000", bg="#ff0000", }, -- lushify_FF0000 xxx guifg=#000000 guibg=#ff0000
    lushify_91087F                         { fg="#ffffff", bg="#91087f", }, -- lushify_91087F xxx guifg=#ffffff guibg=#91087f
    lushify_000000                         { fg="#ffffff", bg="#000000", }, -- lushify_000000 xxx guifg=#ffffff guibg=#000000
    lushify_1A0016                         { fg="#ffffff", bg="#1a0016", }, -- lushify_1A0016 xxx guifg=#ffffff guibg=#1a0016
    lushify_730099                         { fg="#ffffff", bg="#730099", }, -- lushify_730099 xxx guifg=#ffffff guibg=#730099
    lushify_994DB3                         { fg="#000000", bg="#994db3", }, -- lushify_994DB3 xxx guifg=#000000 guibg=#994db3
    lushify_4C2673                         { fg="#ffffff", bg="#4c2673", }, -- lushify_4C2673 xxx guifg=#ffffff guibg=#4c2673
    lushify_6D5DAC                         { fg="#000000", bg="#6d5dac", }, -- lushify_6D5DAC xxx guifg=#000000 guibg=#6d5dac
    lushify_18171C                         { fg="#ffffff", bg="#18171c", }, -- lushify_18171C xxx guifg=#ffffff guibg=#18171c
  }
end)
return theme
